-- IEMAS Database Schema
-- Industrial Energy Monitoring & Analytics System
-- Supabase PostgreSQL Database

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- ============================================================================
-- METERS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS meters (
    meter_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    modbus_config JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE meters IS 'Registered energy meters in the system';
COMMENT ON COLUMN meters.meter_id IS 'Unique identifier for the meter (e.g., MTR-001)';
COMMENT ON COLUMN meters.modbus_config IS 'Modbus configuration including type, baudrate, slave_id, and register mappings';

-- ============================================================================
-- METER READINGS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS meter_readings (
    id BIGSERIAL PRIMARY KEY,
    meter_id VARCHAR(50) NOT NULL REFERENCES meters(meter_id) ON DELETE CASCADE,
    timestamp TIMESTAMP NOT NULL,
    voltage REAL NOT NULL CHECK (voltage >= 0 AND voltage <= 1000),
    current REAL NOT NULL CHECK (current >= 0),
    active_power REAL NOT NULL CHECK (active_power >= 0),
    reactive_power REAL NOT NULL,
    apparent_power REAL NOT NULL CHECK (apparent_power >= 0),
    power_factor REAL NOT NULL CHECK (power_factor >= -1 AND power_factor <= 1),
    frequency REAL NOT NULL CHECK (frequency >= 0 AND frequency <= 100),
    cumulative_energy REAL NOT NULL CHECK (cumulative_energy >= 0),
    firmware_version VARCHAR(50),
    uptime_seconds INTEGER,
    wifi_rssi INTEGER CHECK (wifi_rssi >= -100 AND wifi_rssi <= 0),
    created_at TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE meter_readings IS 'Time-series data of meter readings collected from ESP32 devices';
COMMENT ON COLUMN meter_readings.timestamp IS 'Timestamp when the reading was taken by the meter';
COMMENT ON COLUMN meter_readings.created_at IS 'Timestamp when the reading was stored in database';

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_meter_readings_meter_id ON meter_readings(meter_id);
CREATE INDEX IF NOT EXISTS idx_meter_readings_timestamp ON meter_readings(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_meter_readings_meter_time ON meter_readings(meter_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_meter_readings_created_at ON meter_readings(created_at DESC);

-- ============================================================================
-- THRESHOLDS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS thresholds (
    meter_id VARCHAR(50) PRIMARY KEY REFERENCES meters(meter_id) ON DELETE CASCADE,
    high_power_threshold REAL NOT NULL DEFAULT 10000,
    low_power_factor_threshold REAL NOT NULL DEFAULT 0.8,
    updated_at TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE thresholds IS 'Alert threshold configurations for each meter';
COMMENT ON COLUMN thresholds.high_power_threshold IS 'Power threshold in watts - alert when exceeded';
COMMENT ON COLUMN thresholds.low_power_factor_threshold IS 'Power factor threshold - alert when below this value';

-- ============================================================================
-- ALERTS TABLE
-- ============================================================================
CREATE TABLE IF NOT EXISTS alerts (
    id BIGSERIAL PRIMARY KEY,
    meter_id VARCHAR(50) NOT NULL REFERENCES meters(meter_id) ON DELETE CASCADE,
    alert_type VARCHAR(50) NOT NULL CHECK (alert_type IN ('HIGH_POWER', 'LOW_POWER_FACTOR')),
    measured_value REAL NOT NULL,
    threshold_value REAL NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMP,
    acknowledged_by UUID REFERENCES auth.users(id),
    dismissed BOOLEAN DEFAULT FALSE,
    dismissed_at TIMESTAMP,
    dismissed_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP DEFAULT NOW()
);

COMMENT ON TABLE alerts IS 'Threshold-based alerts generated by the alert system';
COMMENT ON COLUMN alerts.alert_type IS 'Type of alert: HIGH_POWER or LOW_POWER_FACTOR';

-- Indexes for alert queries
CREATE INDEX IF NOT EXISTS idx_alerts_meter_id ON alerts(meter_id);
CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_active ON alerts(meter_id, timestamp) WHERE NOT dismissed;
CREATE INDEX IF NOT EXISTS idx_alerts_type ON alerts(alert_type);

-- ============================================================================
-- FUNCTIONS AND TRIGGERS
-- ============================================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for meters table
DROP TRIGGER IF EXISTS update_meters_updated_at ON meters;
CREATE TRIGGER update_meters_updated_at
    BEFORE UPDATE ON meters
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Trigger for thresholds table
DROP TRIGGER IF EXISTS update_thresholds_updated_at ON thresholds;
CREATE TRIGGER update_thresholds_updated_at
    BEFORE UPDATE ON thresholds
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE meters ENABLE ROW LEVEL SECURITY;
ALTER TABLE meter_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE thresholds ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- Policies for authenticated users (full access for MVP)
-- In production, these should be more restrictive based on organization/role

CREATE POLICY "Allow authenticated users to read meters"
    ON meters FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow authenticated users to manage meters"
    ON meters FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read meter_readings"
    ON meter_readings FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow service role to insert meter_readings"
    ON meter_readings FOR INSERT
    TO service_role
    WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read thresholds"
    ON thresholds FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow authenticated users to manage thresholds"
    ON thresholds FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read alerts"
    ON alerts FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Allow authenticated users to update alerts"
    ON alerts FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Allow service role to insert alerts"
    ON alerts FOR INSERT
    TO service_role
    WITH CHECK (true);

-- ============================================================================
-- INITIAL DATA
-- ============================================================================

-- Insert a sample meter for testing
INSERT INTO meters (meter_id, name, location, modbus_config) 
VALUES (
    'MTR-001',
    'Main Production Line Meter',
    'Factory Floor - Zone A',
    '{
        "type": "RTU",
        "baudrate": 9600,
        "slave_id": 1,
        "registers": {
            "voltage": 0,
            "current": 6,
            "active_power": 12,
            "reactive_power": 18,
            "apparent_power": 24,
            "power_factor": 30,
            "frequency": 36,
            "energy": 42
        }
    }'::jsonb
)
ON CONFLICT (meter_id) DO NOTHING;

-- Insert default thresholds for the sample meter
INSERT INTO thresholds (meter_id, high_power_threshold, low_power_factor_threshold)
VALUES ('MTR-001', 10000, 0.8)
ON CONFLICT (meter_id) DO NOTHING;

-- ============================================================================
-- VIEWS FOR ANALYTICS
-- ============================================================================

-- View: Latest reading per meter
CREATE OR REPLACE VIEW latest_meter_readings AS
SELECT DISTINCT ON (meter_id) 
    meter_readings.*,
    meters.name as meter_name,
    meters.location as meter_location,
    CASE 
        WHEN meter_readings.timestamp > NOW() - INTERVAL '5 minutes' THEN 'online'
        ELSE 'offline'
    END as status
FROM meter_readings
JOIN meters ON meter_readings.meter_id = meters.meter_id
ORDER BY meter_id, timestamp DESC;

COMMENT ON VIEW latest_meter_readings IS 'Latest reading for each meter with online/offline status';

-- View: Active alerts
CREATE OR REPLACE VIEW active_alerts AS
SELECT 
    alerts.*,
    meters.name as meter_name,
    meters.location as meter_location
FROM alerts
JOIN meters ON alerts.meter_id = meters.meter_id
WHERE alerts.dismissed = FALSE
ORDER BY alerts.timestamp DESC;

COMMENT ON VIEW active_alerts IS 'All active (non-dismissed) alerts with meter information';
