-- IEMAS Database - Sample Seed Data
-- Industrial Energy Monitoring & Analytics System

-- Insert sample meters
INSERT INTO meters (meter_id, name, location, modbus_config) VALUES
('METER_001', 'Production Line A - Main', 'Building A, Floor 1', '{"type": "RTU", "baudrate": 9600, "slave_id": 1}'),
('METER_002', 'HVAC System', 'Building A, Roof', '{"type": "RTU", "baudrate": 9600, "slave_id": 2}'),
('METER_003', 'Packaging Unit', 'Building B, Floor 1', '{"type": "RTU", "baudrate": 9600, "slave_id": 3}')
ON CONFLICT (meter_id) DO NOTHING;

-- Insert default thresholds for sample meters
INSERT INTO thresholds (meter_id, high_power_threshold, low_power_factor_threshold) VALUES
('METER_001', 15000, 0.85),
('METER_002', 8000, 0.80),
('METER_003', 12000, 0.85)
ON CONFLICT (meter_id) DO UPDATE SET
    high_power_threshold = EXCLUDED.high_power_threshold,
    low_power_factor_threshold = EXCLUDED.low_power_factor_threshold;

-- Note: Sample meter readings and alerts would be generated by ESP32 devices and the backend system
-- This seed file only sets up the initial meter registrations
