'use client'

import React, { useState, useMemo } from 'react'
import { Sparkles, DollarSign, Leaf, RefreshCw, Layers } from 'lucide-react'
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, Cell } from 'recharts'

export default function SavingsCalculator() {
  const [bill, setBill] = useState(15000)
  const [currentPF, setCurrentPF] = useState(0.74)
  const [targetPF, setTargetPF] = useState(0.98)

  const calculations = useMemo(() => {
    const basePenaltyFactor = 0.85
    const penaltyRate = currentPF < basePenaltyFactor ? (basePenaltyFactor - currentPF) * 1.5 : 0
    const monthlyPenalty = bill * penaltyRate

    const demandBillPortion = bill * 0.25
    const kvaDemandOverhead = demandBillPortion * ((targetPF / currentPF) - 1)

    const monthlySavings = monthlyPenalty + kvaDemandOverhead
    const annualSavings = monthlySavings * 12

    const approxLoadKW = (bill / 0.12) / 720
    const tanPhiCurrent = Math.tan(Math.acos(currentPF))
    const tanPhiTarget = Math.tan(Math.acos(targetPF))
    const kvarNeeded = Math.max(0, approxLoadKW * (tanPhiCurrent - tanPhiTarget))
    const capBankCost = Math.round(kvarNeeded * 45 + 1200)

    const paybackMonths = annualSavings > 0 ? (capBankCost / (annualSavings / 12)) : 0

    const totalMonthlyKWh = bill / 0.12
    const lineLossPercent = 0.04 
    const lossesAvoidedKWh = totalMonthlyKWh * lineLossPercent * (1 - Math.pow(currentPF / targetPF, 2))
    const co2TonsAnnual = (lossesAvoidedKWh * 12 * 0.45) / 1000
    const treesEquivalent = co2TonsAnnual * 16.5 

    return {
      monthlyPenalty: Math.round(monthlyPenalty),
      kvaOverhead: Math.round(kvaDemandOverhead),
      totalSavingsMonthly: Math.round(monthlySavings),
      annualSavings: Math.round(annualSavings),
      capBankCost: Math.round(capBankCost),
      paybackMonths: +paybackMonths.toFixed(1),
      co2Tons: +co2TonsAnnual.toFixed(1),
      trees: Math.round(treesEquivalent),
      kvarNeeded: Math.round(kvarNeeded)
    }
  }, [bill, currentPF, targetPF])

  const chartData = [
    { name: 'Before Correction', cost: calculations.monthlyPenalty + calculations.kvaOverhead, color: '#F59E0B' },
    { name: 'After Correction', cost: 0, color: '#2DD4BF' }
  ]

  return (
    <div className="w-full bg-surface border border-border rounded-3xl p-6 md:p-8 shadow-xl">
      
      {/* Header Info */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div>
          <span className="px-3 py-1 bg-surface-2 border border-border text-teal-accent text-[0.7rem] uppercase tracking-[0.15em] font-mono rounded-full inline-flex items-center gap-1.5 mb-2">
            <Leaf className="w-3.5 h-3.5 text-teal-accent" /> Facility Sustainability & ROI Calculator
          </span>
          <h3 className="text-xl font-bold font-display text-text-1">Power Factor ROI Calculator</h3>
          <p className="text-text-2 text-xs sm:text-sm mt-1 font-sans">
            Determine financial payback margins and carbon offsets generated by improving electrical power quality.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
        
        {/* Sliders (Left Panel) */}
        <div className="lg:col-span-4 space-y-6 bg-surface-2 border border-border p-5 rounded-2xl">
          <h4 className="text-xs font-bold text-text-3 uppercase tracking-widest pb-2 border-b border-border font-mono">Parameters</h4>
          
          {/* Monthly Utility Bill */}
          <div className="space-y-1.5 font-mono">
            <div className="flex justify-between text-xs">
              <span className="text-text-2">Monthly Energy Bill</span>
              <span className="text-text-1 font-bold">${bill.toLocaleString()}</span>
            </div>
            <input 
              type="range" 
              min="2000" 
              max="100000" 
              step="1000"
              value={bill} 
              onChange={(e) => setBill(Number(e.target.value))}
              className="w-full h-1 bg-border rounded-lg appearance-none cursor-pointer accent-teal-accent"
            />
            <div className="flex justify-between text-[9px] text-text-3">
              <span>$2,000</span>
              <span>$100,000</span>
            </div>
          </div>

          {/* Current PF slider */}
          <div className="space-y-1.5 font-mono">
            <div className="flex justify-between text-xs">
              <span className="text-text-2">Current Power Factor</span>
              <span className="text-amber-accent font-bold">{currentPF}</span>
            </div>
            <input 
              type="range" 
              min="0.60" 
              max="0.95" 
              step="0.01"
              value={currentPF} 
              onChange={(e) => setCurrentPF(Number(e.target.value))}
              className="w-full h-1 bg-border rounded-lg appearance-none cursor-pointer accent-amber-accent"
            />
            <div className="flex justify-between text-[9px] text-text-3">
              <span>0.60 (Lagging)</span>
              <span>0.95 (Good)</span>
            </div>
          </div>

          {/* Target PF slider */}
          <div className="space-y-1.5 font-mono">
            <div className="flex justify-between text-xs">
              <span className="text-text-2">Target Power Factor</span>
              <span className="text-teal-accent font-bold">{targetPF}</span>
            </div>
            <input 
              type="range" 
              min="0.90" 
              max="1.00" 
              step="0.01"
              value={targetPF} 
              onChange={(e) => setTargetPF(Number(e.target.value))}
              className="w-full h-1 bg-border rounded-lg appearance-none cursor-pointer accent-teal-accent"
            />
            <div className="flex justify-between text-[9px] text-text-3">
              <span>0.90 Target</span>
              <span>1.00 (Unity)</span>
            </div>
          </div>

          <div className="bg-surface p-3.5 rounded-xl border border-border text-xs leading-relaxed text-text-2 shadow-sm font-sans">
            <span className="font-bold text-text-1">Capacitor Stage Required:</span>
            <p className="mt-1 font-mono text-[11px]">
              To close this reactive gap, you will require an estimated <span className="text-teal-accent font-bold">{calculations.kvarNeeded} kVAR</span> capacitor step setup.
            </p>
          </div>
        </div>

        {/* Output Metrics (Right Panel) */}
        <div className="lg:col-span-8 flex flex-col justify-between space-y-6">
          
          {/* Output Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            
            {/* Savings card */}
            <div className="bg-surface-2 border border-border p-4 rounded-2xl relative overflow-hidden">
              <div className="w-9 h-9 rounded-xl bg-surface border border-border flex items-center justify-center text-teal-accent mb-3 shadow-sm">
                <DollarSign className="w-5 h-5" />
              </div>
              <div className="text-[10px] text-text-3 font-bold uppercase tracking-wider font-mono">Annual Surcharge Avoided</div>
              <div className="text-xl font-bold text-text-1 mt-1 font-mono">${calculations.annualSavings.toLocaleString()}</div>
              <div className="text-[10px] text-text-2 mt-2 font-mono">
                Saves <span className="text-teal-accent font-bold">${calculations.totalSavingsMonthly} / mo</span>.
              </div>
            </div>

            {/* Payback period card */}
            <div className="bg-surface-2 border border-border p-4 rounded-2xl relative overflow-hidden">
              <div className="w-9 h-9 rounded-xl bg-surface border border-border flex items-center justify-center text-teal-accent mb-3 shadow-sm">
                <RefreshCw className="w-5 h-5" />
              </div>
              <div className="text-[10px] text-text-3 font-bold uppercase tracking-wider font-mono">Estimated Payback Period</div>
              <div className="text-xl font-bold text-text-1 mt-1 font-mono">
                {calculations.paybackMonths} {calculations.paybackMonths === 1 ? 'Month' : 'Months'}
              </div>
              <div className="text-[10px] text-text-2 mt-2 font-mono">
                APFC bank cost: <span className="text-teal-accent font-bold">${calculations.capBankCost.toLocaleString()}</span>
              </div>
            </div>

            {/* Carbon card */}
            <div className="bg-surface-2 border border-border p-4 rounded-2xl relative overflow-hidden">
              <div className="w-9 h-9 rounded-xl bg-surface border border-border flex items-center justify-center text-teal-accent mb-3 shadow-sm">
                <Leaf className="w-5 h-5" />
              </div>
              <div className="text-[10px] text-text-3 font-bold uppercase tracking-wider font-mono">Carbon Offset Potential</div>
              <div className="text-xl font-bold text-teal-accent mt-1 font-mono">
                {calculations.co2Tons} Tons CO₂
              </div>
              <div className="text-[10px] text-text-2 mt-2 font-mono">
                Equivalent to <span className="text-teal-accent font-bold">{calculations.trees}</span> trees / yr.
              </div>
            </div>

          </div>

          {/* Surcharges breakdown box */}
          <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center bg-surface-2 border border-border p-5 rounded-2xl flex-grow">
            
            <div className="md:col-span-7 space-y-4">
              <h4 className="text-xs font-bold text-text-2 uppercase tracking-wider flex items-center gap-1.5 font-mono">
                <Layers className="w-3.5 h-3.5 text-teal-accent" /> Utility Bill Surcharge Avoidance Profile
              </h4>
              
              <div className="space-y-3.5 text-xs text-text-2 leading-relaxed font-sans">
                <p>
                  Industrial electricity distributors apply line surcharges when power factor drops below <span className="font-bold text-text-1">0.85</span>. Low PF draws high reactive current which overloads local transformer windings.
                </p>
                <div className="flex flex-col gap-2 bg-surface p-3.5 rounded-xl border border-border font-mono">
                  <div className="flex justify-between">
                    <span>Power Quality Surcharge Penalty:</span>
                    <span className="text-amber-accent font-bold">${calculations.monthlyPenalty} / mo</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Excess Demand (kVA Surcharge):</span>
                    <span className="text-amber-accent font-bold">${calculations.kvaOverhead} / mo</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="md:col-span-5 h-[150px] w-full flex items-center justify-center bg-surface border border-border rounded-xl p-2 shadow-inner">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ left: -10, top: 10, right: 10, bottom: 5 }}>
                  <XAxis dataKey="name" stroke="#4A5A6B" fontSize={9} tickLine={false} />
                  <YAxis stroke="#4A5A6B" fontSize={9} tickLine={false} />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#0F1519', borderColor: '#1E2D38', fontSize: '10px' }}
                    itemStyle={{ color: '#000' }}
                  />
                  <Bar dataKey="cost" fill="#F59E0B" radius={[4, 4, 0, 0]} barSize={40}>
                    {chartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>

          </div>

        </div>

      </div>
    </div>
  )
}
